### PR TITLE
Detect AAR minSdkVersion and pass it to dx

### LINKED ISSUE #310: Kotlin static interface method
Using the latest version of DexCount (1.0.3) and a static kotlin interface method like this:
```kotlin
interface Foo {
    fun onComplete()

    companion object {
        private class FooImpl(private val onComplete: () -> Unit) : Foo {
            override fun onComplete() {
                this.onComplete.invoke()
            }
        }

        @JvmStatic
        fun onPlaybackCompletedListener(onComplete: () -> Unit): Foo {
            return FooImpl(onComplete)
        }
    }
}

```
I am seeing dexCount throw exceptions like these:
```
> Task :app:countQaDebugDexMethods
Error counting dex methods. Please contact the developer at https://github.com/KeepSafe/dexcount-gradle-plugin/issues
com.getkeepsafe.dexcount.DexCountException: dx exited with exit code 1
stderr=WARNING in com.example.Foo.onPlaybackCompletedListener:(Lkotlin/jvm/functions/Function0;)Lcom/example/Foo;: defining a static interface method requires --min-sdk-version >= 24 (currently 13) for interface methods: com.example.Foo.onPlaybackCompletedListener:(Lkotlin/jvm/functions/Function0;)Lcom/example/Foo;
Uncaught translation error: com.android.dx.cf.code.SimException: ERROR in com.example.Foo.onPlaybackCompletedListener:(Lkotlin/jvm/functions/Function0;)Lcom/example/Foo;: invoking a static interface method com.example.Foo.$jacocoInit:()[Z strictly requires --min-sdk-version >= 24 (blocked at current API level 13)
1 error; aborting

        at com.getkeepsafe.dexcount.DexFile$Companion.extractDexFromAar(SourceFile.kt:165)
        at com.getkeepsafe.dexcount.DexFile$Companion.extractDexData(SourceFile.kt:99)
        at com.getkeepsafe.dexcount.DexCountTask.generatePackageTree(DexCountTask.kt:172)
        at com.getkeepsafe.dexcount.DexCountTask.execute(DexCountTask.kt:129)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:49)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:42)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:726)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:693)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.run(ExecuteActionsTaskExecuter.java:569)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:395)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:387)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:242)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:150)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:84)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:554)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:537)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$300(ExecuteActionsTaskExecuter.java:108)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.executeWithPreviousOutputFiles(ExecuteActionsTaskExecuter.java:278)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:267)
        at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$1(ExecuteStep.java:33)
        at java.util.Optional.orElseGet(Optional.java:267)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:33)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:67)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:36)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:49)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:34)
        at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:43)
        at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
        at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
        at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:34)
        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:44)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:54)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:38)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
        at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:159)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:72)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:43)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:44)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:33)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:92)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:85)
        at java.util.Optional.map(Optional.java:215)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:55)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:39)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:94)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:49)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:79)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:53)
        at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:74)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.lambda$execute$2(SkipEmptyWorkStep.java:78)
        at java.util.Optional.orElseGet(Optional.java:267)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:78)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:34)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:39)
        at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:40)
        at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:28)
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:194)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:186)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:114)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:409)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:399)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:242)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:150)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:94)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:356)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.lang.Thread.run(Thread.java:748)
```
Note that the exception claims the current API level was 13, even though for this test run I set the min sdk version to 25. This is in an android project with multiple flavor dimensions, but the exception is thrown regardless of which flavor or variant is used.

### PR DESCRIPTION
**Pull request by benjamin-bader**
This is such a hack, but then so is AAR method counting so whatevs

Fixes #310

### CODE REVIEW

File: src/main/kotlin/com/getkeepsafe/dexcount/SourceFile.kt [hunk 1]
```diff
@@ -111,11 +111,27 @@ internal class DexFile(
...
             // unzip classes.jar from the AAR
+            var minSdk = 13 // the default minSdkVersion of dx
             val tempClasses = file.unzip { entries ->
-                val jarFile = entries.find { it.name.matches(Regex("classes\\.jar")) }
-                makeTempFile("classes.jar").also {
-                    jarFile!!.writeTo(it)
+                var tempFile: File? = null
+
+                for (entry in entries) {
+                    if (entry.name == "AndroidManifest.xml") {
```
Comment (nikwotton) [inline src/main/kotlin/com/getkeepsafe/dexcount/SourceFile.kt:119]: Correct me if I'm wrong, but this would only work if the minSdk is defined in the manifest rather than in the build.gradle(.kts) where it is often defined, right?

File: src/main/kotlin/com/getkeepsafe/dexcount/SourceFile.kt [hunk 2]
```diff
@@ -111,11 +111,27 @@ internal class DexFile(
...
+                        if (match != null) {
+                            minSdk = match.groupValues[1].toInt()
+                        }
+                    }
+
+                    if (entry.name.matches(Regex("classes\\.jar"))) {
+                        tempFile = makeTempFile("classes.jar").also {
+                            entry.writeTo(it)
+                        }
+                    }
```
Comment (nikwotton) [inline src/main/kotlin/com/getkeepsafe/dexcount/SourceFile.kt:131]: Neither yours nor mine works if a variable is used for the min sdk, but this is a step closer:
```suggestion
                    when {
                        entry.name == "AndroidManifest.xml" -> {
                            val manifestText = entry.inputStream().bufferedReader().use { it.readText() }
                            val match = Regex("""android:minSdkVersion="(\d+)"""").find(manifestText)
                            if (match != null) {
                                minSdk = match.groupValues[1].toInt()
                            }
                        }
                        entry.name == "build.gradle" -> {
                            val gradleText = entry.inputStream().bufferedReader().use { it.readText() }
                            val match = Regex("""minSdkVersion (\d+)""").find(gradleText)
                            if (match != null) {
                                minSdk = match.groupValues[1].toInt()
                            }
                        }
                        entry.name == "build.gradle.kts" -> {
                            val gradleText = entry.inputStream().bufferedReader().use { it.readText() }
                            val match = Regex("""minSdkVersion\((\d+)\)""").find(gradleText)
                            if (match != null) {
                                minSdk = match.groupValues[1].toInt()
                            }
                        }
                        entry.name == "build.gradle.kts" -> {

                        }
                        entry.name.matches(Regex("classes\\.jar")) -> {
                            tempFile = makeTempFile("classes.jar").also {
                                entry.writeTo(it)
                            }
                        }
                    }
```

File: src/main/kotlin/com/getkeepsafe/dexcount/SourceFile.kt (hunk 1 above)
Comment (benjamin-bader) [reply src/main/kotlin/com/getkeepsafe/dexcount/SourceFile.kt:119]: Build files (build.gradle and build.gradle.kts) are used to assemble an `.aar` archive, but are not included in it.  The values you define in those build files are _placed into_ the manifest file, where we can reliably read them.

CI is failing here because evidently, the version of `dx` used in CI doesn't have the `--min-sdk-version` option, so now I need to figure out when that flag was added, and conditionally use that option only if it exists.

Comment (benjamin-bader) [reply src/main/kotlin/com/getkeepsafe/dexcount/SourceFile.kt:119]: If you doubt this, check our integration tests.  In `integration/lib/build.gradle` you'll certainly find the `minSdkVersion` defined there, and not in `./src/main/AndroidManifest.xml`.

File: src/main/kotlin/com/getkeepsafe/dexcount/SourceFile.kt (hunk 2 above)
Comment (benjamin-bader) [reply src/main/kotlin/com/getkeepsafe/dexcount/SourceFile.kt:131]: Thanks for taking the time to write this out, but see my other comment for why I will regretfully decline this patch.

File: src/main/kotlin/com/getkeepsafe/dexcount/SourceFile.kt (hunk 1 above)
Comment (nikwotton) [reply src/main/kotlin/com/getkeepsafe/dexcount/SourceFile.kt:119]: Ah, excellent point - I'm not terribly used to working with pre-built archives so I overlooked that. I'll take a look at the new build you published and see if it works. Thanks for being so quick to put in this fix!
